# Generated by Django 4.1.3 on 2022-12-29 09:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('hazai', 'hazai'), ('kulfoldi', 'kulfoldi'), ('utazas', 'utazas')], max_length=200)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('date_of_hike', models.DateField(null=True)),
                ('intro', models.TextField(null=True)),
                ('distance_in_km', models.IntegerField(null=True)),
                ('altitude_in_m', models.IntegerField(null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(to='hobbiturazas.tag')),
            ],
        ),
    ]
